/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minor.project;

/**
 *
 * @author Abhishek verma
 */
public class Homeapp extends javax.swing.JFrame {

    /**
     * Creates new form Homeapp
     */
    public Homeapp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        cb3 = new javax.swing.JCheckBox();
        cb4 = new javax.swing.JCheckBox();
        cb5 = new javax.swing.JCheckBox();
        cb6 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Home-Appliance Products");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 20, 490, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Select your product : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 100, 200, 30);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abhishek verma\\Downloads\\SHAREit\\SM-G360H\\photo\\okay.jpg")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(310, 280, 90, 40);

        cb1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb1.setForeground(new java.awt.Color(0, 0, 204));
        cb1.setText("Refrigerator");
        jPanel1.add(cb1);
        cb1.setBounds(280, 110, 120, 25);

        cb2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb2.setForeground(new java.awt.Color(0, 0, 204));
        cb2.setText("Microwave");
        jPanel1.add(cb2);
        cb2.setBounds(450, 110, 110, 25);

        cb3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb3.setForeground(new java.awt.Color(0, 0, 204));
        cb3.setText("Sewing Machine");
        cb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3ActionPerformed(evt);
            }
        });
        jPanel1.add(cb3);
        cb3.setBounds(280, 160, 140, 25);

        cb4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb4.setForeground(new java.awt.Color(0, 0, 204));
        cb4.setText("Washing Machine");
        cb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb4ActionPerformed(evt);
            }
        });
        jPanel1.add(cb4);
        cb4.setBounds(450, 160, 150, 25);

        cb5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb5.setForeground(new java.awt.Color(0, 0, 204));
        cb5.setText("Kitchen Appleances");
        jPanel1.add(cb5);
        cb5.setBounds(280, 210, 160, 25);

        cb6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb6.setForeground(new java.awt.Color(0, 0, 255));
        cb6.setText("Hair Styling ");
        jPanel1.add(cb6);
        cb6.setBounds(460, 210, 110, 25);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abhishek verma\\Downloads\\SHAREit\\SM-G360H\\photo\\bbtn2.jpg")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 10, 60, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abhishek verma\\Downloads\\SHAREit\\SM-G360H\\photo\\Homeapp.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 if(cb1.isSelected())
 {
     refrigerator rf= new refrigerator();
     rf.setVisible(true);
     this.setVisible(false);
 }  
 else if(cb2.isSelected())
 {
     Microwave rf= new Microwave();
     rf.setVisible(true);
     this.setVisible(false);
 }
  else if(cb3.isSelected())
 {
    SewingMachine rf= new SewingMachine();
     rf.setVisible(true);
     this.setVisible(false);
 }
  else if(cb4.isSelected())
 {
       WashingMachine rf= new WashingMachine();
     rf.setVisible(true);
     this.setVisible(false);
 }
  else if(cb5.isSelected())
 {
     Kitchen rf= new Kitchen();
     rf.setVisible(true);
     this.setVisible(false);
 }
  else if(cb6.isSelected())
 {
     HairStyle rf= new HairStyle();
     rf.setVisible(true);
     this.setVisible(false);
 }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb3ActionPerformed

    private void cb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
welcome wc= new welcome();
wc.setVisible(true);
this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homeapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homeapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homeapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homeapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homeapp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JCheckBox cb4;
    private javax.swing.JCheckBox cb5;
    private javax.swing.JCheckBox cb6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
